export const concert = {
  band: 'ASDF',
  event: '1st Live',
  date: '2026. 03. 28 SAT',
  time: '18:00',
  venue: '록커스 가든',
  venueEn: 'Rockers Garden',
  code: '799355',
  address: '서울 강남구 도곡로4길 5 지하1층',
  tagline: '똑딱똑딱 코딩 대신 신나는 록앤롤!',
}

export const setlist = [
  {
    no: 1,
    title: '버터플라이',
    part: '1부',
    tag: '',
    session: [
      { role: '보컬',      members: ['고우리', '김정용'] },
      { role: '기타 1·2',  members: ['최철호', '이한솔'] },
      { role: '베이스',    members: ['김현민'] },
      { role: '키보드 1·2', members: ['정현석', '고우리'] },
      { role: '드럼',      members: ['박정재'] },
    ],
  },
  {
    no: 2,
    title: '나는나비',
    part: '1부',
    tag: '',
    session: [
      { role: '보컬',     members: ['김정용'] },
      { role: '기타 1·2', members: ['최철호', '이한솔'] },
      { role: '베이스',   members: ['김현민'] },
      { role: '키보드',   members: ['정현석'] },
      { role: '드럼',     members: ['박정재'] },
    ],
  },
  {
    no: 3,
    title: 'Love Poem',
    part: '1부',
    tag: '',
    session: [
      { role: '보컬 · 키보드', members: ['고우리'] },
      { role: '기타 1·2',     members: ['최철호', '이한솔'] },
      { role: '베이스',        members: ['김현민'] },
      { role: '드럼',          members: ['박정재'] },
    ],
  },
  {
    no: 4,
    title: 'Creep',
    part: '1부',
    tag: '',
    session: [
      { role: '보컬',     members: ['김정용'] },
      { role: '기타 1·2', members: ['최철호', '이한솔'] },
      { role: '베이스',   members: ['고우리'] },
      { role: '드럼',     members: ['박정재'] },
    ],
  },
  {
    no: 5,
    title: '말하는대로',
    part: '1부',
    tag: '',
    session: [
      { role: '보컬',   members: ['정현석', '이한솔'] },
      { role: '키보드', members: ['고우리'] },
      { role: '드럼',   members: ['박정재'] },
    ],
  },
  {
    no: 6,
    title: "60's cardin",
    part: '2부',
    tag: '',
    session: [
      { role: '보컬',      members: ['김정용'] },
      { role: '기타',      members: ['박정호'] },
      { role: '베이스',    members: ['김현민'] },
      { role: '키보드 1·2', members: ['정현석', '고우리'] },
      { role: '드럼',      members: ['박정재'] },
    ],
  },
  {
    no: 7,
    title: '마흔다섯 마흔하나',
    part: '2부',
    tag: '',
    session: [
      { role: '보컬 · 키보드', members: ['고우리'] },
      { role: '기타 1·2',     members: ['이한솔', '최철호'] },
      { role: '베이스',        members: ['김현민'] },
      { role: '키보드',        members: ['정현석'] },
      { role: '드럼',          members: ['박정재'] },
    ],
  },
  {
    no: 8,
    title: "It's my life",
    part: '2부',
    tag: '',
    session: [
      { role: '보컬',     members: ['김정용'] },
      { role: '기타 1·2', members: ['최철호', '이한솔'] },
      { role: '베이스',   members: ['고우리'] },
      { role: '키보드',   members: ['정현석'] },
    ],
  },
  {
    no: 9,
    title: '벚꽃엔딩',
    part: '2부',
    tag: '',
    session: [
      { role: '보컬',    members: ['이한솔'] },
      { role: '기타',    members: ['최철호'] },
      { role: '베이스',  members: ['김현민'] },
      { role: '키보드',  members: ['정현석'] },
      { role: '드럼',    members: ['박정재'] },
      { role: '바이올린', members: ['차지민'] },
    ],
  },
  {
    no: 10,
    title: '너에게난 나에게넌',
    part: '2부',
    tag: '',
    session: [
      { role: '보컬',      members: ['김정용', '고우리'] },
      { role: '기타 1·2',  members: ['최철호', '이한솔'] },
      { role: '베이스',    members: ['김현민'] },
      { role: '키보드 1·2', members: ['정현석', '고우리'] },
      { role: '드럼',      members: ['박정재'] },
    ],
  },
]

export const members = [
  {
    name: '김정용',
    nickname: 'Ctrl+Alt+Del',
    role: '메인 보컬',
    color: '#FF8C00',
    desc: '코딩도 인생도 리셋이 답이다',
    photo: '/김정용.jpg',
  },
  {
    name: '최철호',
    nickname: '404',
    role: '기타',
    color: '#00CFFF',
    desc: '잃어버린 음을 찾아서',
    photo: '/최철호.jpg',
  },
  {
    name: '이한솔',
    nickname: 'FORK',
    role: '기타 · 보컬',
    color: '#F7C325',
    desc: 'git fork origin/soul — 나만의 브랜치로 산다',
    photo: '/이한솔.jpg',
  },
  {
    name: '고우리',
    nickname: 'SYNTH-AXIS',
    role: '키보드 · 베이스 · 보컬',
    color: '#9B4DFF',
    desc: '주파수를 지배하는 자',
    photo: '/고우리.jpg',
  },
  {
    name: '정현석',
    nickname: 'ECHO',
    role: '키보드 · 보컬',
    color: '#FF69B4',
    desc: 'echo $THOUGHTS | grep "집중" — no matches found',
    photo: '/정현석.jpg',
  },
  {
    name: '김현민',
    nickname: 'NULL',
    role: '베이스',
    color: '#00FF7F',
    desc: '비어있는 듯 꽉 찬 저음',
    photo: '/김현민.jpg',
  },
  {
    name: '박정재',
    nickname: 'LOOP',
    role: '창립자 · 단장 · 드럼',
    color: '#FF4444',
    desc: 'while(true) { rock(); }',
    photo: '/박정재.jpg',
  },
  {
    name: '박정호',
    nickname: 'GREP',
    role: '기타',
    color: '#20B2AA',
    desc: 'grep -r "완벽한 리프" . — 항상 매칭',
    photo: '/박정호.jpg',
  },
  {
    name: '차지민',
    nickname: 'INTERRUPT',
    role: '바이올린',
    color: '#C0C0C0',
    desc: "import { 차지민 } from 'FORK'",
    secret: true,
  },
]
