export const concert = {
  band: 'ASDF',
  event: '1st Live',
  date: '2026. 03. 28 SAT',
  time: '18:00',
  venue: '록커스 가든',
  venueEn: 'Rockers Garden',
  code: '799355',
  address: '서울 강남구 도곡로4길 5 지하1층',
  tagline: '똑딱똑딱 코딩 대신 신나는 록앤롤!',
}

export const setlist = [
  { no: 1,  title: 'Hello, World!',           tag: '오프닝' },
  { no: 2,  title: 'Stack Overflow',           tag: '' },
  { no: 3,  title: 'Git Push (My Heart)',      tag: '' },
  { no: 4,  title: '404 (사랑을 찾지 못했어)', tag: '' },
  { no: 5,  title: 'Infinite Loop',            tag: '' },
  { no: 6,  title: 'Debug Night',              tag: '' },
  { no: 7,  title: 'Null Pointer',             tag: '' },
  { no: 8,  title: 'Runtime Error',            tag: '' },
  { no: 9,  title: 'Ctrl+Alt+Del',             tag: '타이틀곡' },
  { no: 10, title: 'ASDF',                     tag: '앙코르' },
]

export const members = [
  {
    name: '김정용',
    nickname: 'Ctrl+Alt+Del',
    role: '메인 보컬',
    color: '#FF8C00',
    desc: '코딩도 인생도 리셋이 답이다',
    photo: '/김정용.jpg',
  },
  {
    name: '최철호',
    nickname: '404',
    role: '기타',
    color: '#00CFFF',
    desc: '잃어버린 음을 찾아서',
    photo: '/최철호.jpg',
  },
  {
    name: '이한솔',
    nickname: 'FORK',
    role: '기타 · 보컬',
    color: '#F7C325',
    desc: 'git fork origin/soul — 나만의 브랜치로 산다',
    photo: '/이한솔.jpg',
  },
  {
    name: '고우리',
    nickname: 'SYNTH-AXIS',
    role: '키보드 · 베이스 · 보컬',
    color: '#9B4DFF',
    desc: '주파수를 지배하는 자',
    photo: '/고우리.jpg',
  },
  {
    name: '정현석',
    nickname: 'ECHO',
    role: '키보드 · 보컬',
    color: '#FF69B4',
    desc: 'echo $THOUGHTS | grep "집중" — no matches found',
    photo: '/정현석.jpg',
  },
  {
    name: '김현민',
    nickname: 'NULL',
    role: '베이스',
    color: '#00FF7F',
    desc: '비어있는 듯 꽉 찬 저음',
    photo: '/김현민.jpg',
  },
  {
    name: '박정재',
    nickname: 'LOOP',
    role: '창립자 · 단장 · 드럼',
    color: '#FF4444',
    desc: 'while(true) { rock(); }',
  },
  {
    name: '박정호',
    nickname: 'GREP',
    role: '기타',
    color: '#20B2AA',
    desc: 'grep -r "완벽한 리프" . — 항상 매칭',
    photo: '/박정호.jpg',
    absent: true,
  },
  {
    name: '박규민',
    nickname: 'REBOOT',
    role: '보컬 · 드럼',
    color: '#FF6B6B',
    desc: '막내지만 비트는 제일 세다 — youngest.exe',
    absent: true,
  },
  {
    name: '차지민',
    nickname: 'INTERRUPT',
    role: '바이올린',
    color: '#C0C0C0',
    desc: "import { 차지민 } from 'FORK'",
    secret: true,
  },
]
