export const concert = {
  band: 'ASDF',
  event: '1st Live',
  date: '2026. 03. 28 SAT',
  time: '18:00',
  venue: '록커스 가든',
  venueEn: 'Rockers Garden',
  code: '799355',
  address: '서울 강남구 도곡로4길 5 지하1층',
  tagline: '똑딱똑딱 코딩 대신 신나는 록앤롤!',
}

export const setlist = [
  { no: 1,  title: 'Hello, World!',           tag: '오프닝' },
  { no: 2,  title: 'Stack Overflow',           tag: '' },
  { no: 3,  title: 'Git Push (My Heart)',      tag: '' },
  { no: 4,  title: '404 (사랑을 찾지 못했어)', tag: '' },
  { no: 5,  title: 'Infinite Loop',            tag: '' },
  { no: 6,  title: 'Debug Night',              tag: '' },
  { no: 7,  title: 'Null Pointer',             tag: '' },
  { no: 8,  title: 'Runtime Error',            tag: '' },
  { no: 9,  title: 'Ctrl+Alt+Del',             tag: '타이틀곡' },
  { no: 10, title: 'ASDF',                     tag: '앙코르' },
]

export const members = [
  {
    name: '김정용',
    nickname: 'Ctrl+Alt+Del',
    role: '메인 보컬',
    color: '#FF8C00',
    desc: '코딩도 인생도 리셋이 답이다',
  },
  {
    name: '최철호',
    nickname: '404',
    role: '기타',
    color: '#00CFFF',
    desc: '잃어버린 음을 찾아서',
  },
  {
    name: '이한솔',
    nickname: 'FORK',
    role: '기타 · 보컬',
    color: '#F7C325',
    desc: '코드도 음도, 갈래가 많을수록 풍성해진다',
  },
  {
    name: '고우리',
    nickname: 'SYNTH-AXIS',
    role: '키보드 · 베이스 · 보컬',
    color: '#9B4DFF',
    desc: '주파수를 지배하는 자',
  },
  {
    name: '정현석',
    nickname: 'ECHO',
    role: '키보드 · 보컬',
    color: '#FF69B4',
    desc: '건반 위의 울림이 무대를 가득 채운다',
  },
  {
    name: '김현민',
    nickname: 'NULL',
    role: '베이스',
    color: '#00FF7F',
    desc: '비어있는 듯 꽉 찬 저음',
  },
  {
    name: '박정재',
    nickname: 'LOOP',
    role: '드럼',
    color: '#FF4444',
    desc: 'while(true) { rock(); }',
  },
  {
    name: '박정호',
    nickname: 'GREP',
    role: '기타',
    color: '#20B2AA',
    desc: '정확한 음만 골라내는 손가락',
  },
  {
    name: '차지민',
    nickname: 'INTERRUPT',
    role: '바이올린',
    color: '#C0C0C0',
    desc: '공연이 시작되어야 보이는 존재',
    secret: true,
  },
]
